name: My-Test

on:
  push:
    branches:
      - master

jobs:
  my-testing:
    runs-on: ubunty-latest

    steps:
    - name: Print Hello Message
      run: echo "Hello World Testing Job"
        
  my-deploy:
    runs-on: ubunty-latest

    steps:
    - name: Print Hello Message
      run: echo "Hello World Deploy Job"
