name: My-Test
env:
  APPLICATION_NAME: "MyFlask"
  PACKAGE_NAME: "flask-deploy-ver-${{github.sha}}

on:
  push:
    branches:
      - master

jobs:
  my-testing:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello Message
      run: echo "Hello World Testing Job"
      
    
  my-deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]

    steps:
    - name: Print Hello Message
      run: echo "Hello World Deploy Job"
      
    - name: Printing Deployment packege
      run: |
        echo "Deploy packege name is ${{env.PACKAGE_NAME}}"
