# This is a basic workflow to help you get started with Actions

name: My-Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  my-testing:
      runs-on: ubunty-latest
      
      steps:
      - name: Print Hello Message
        run: echo "Hello World Testing Job"
        
  my-deploy:
      runs-on: ubunty-latest
      
      steps:
      - name: Print Hello Message
        run: echo "Hello World Deploy Job"
